server:
  port: 81
  servlet:
    encoding:
      force: true
      charset: UTF-8
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/house-rent-manage?serverTimezone=UTC
    username: root
    password: 123456
logging:
  level:
    com:
      zzc:
        mapper: debug
#mybatis:
#  type-aliases-package: com.zzc.entity
#
#pagehelper:
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql